version: '3'
services:
  app:
    build: .
    ports:
      - 4000:4000
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo/encurtador_de_url
  mongo:
    image: mongo
    ports:
      - 27018:27017